### ISSUE TITLE
tracking issue for `encoding` future

### ISSUE THREAD

**Issue by vldm** [exonum/exonum#148]
First level of `storage_value!` and `message!` refactor was a bit cosmetic. But for future usage we should make some architecture changes that will make it better in usability and in performance.

1. Remove redurant variable `to` from `Field`'s methods signature.
2. Investigate if we could remove `from` too.
3. Our buffer could be smart enough to read primitive types, this will give better API for end user.
4. Some investigation is important, to make `stream_struct` closer to Rust type system.
(status of procedural macros, const fn's, may be user should be possible to take make structure without our macros)
5. Remove `WriteBufferWrapper` and modify name of methods, "write" associated with `std::Write`

## Parsed list of all todos:

 - [ ] TODO: Check this message after refactor buffer.  [error.rs#9](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/error.rs#9)
 - [ ] TODO: Remove `to` from `Field` signature, it's a bit redurant.  [error.rs#17](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/error.rs#17)
 - [x] TODO: this check should be rewritted as part of buffer implementation.  [fields.rs#103](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/fields.rs#103)
 - [ ] TODO: use Read and Cursor  [fields.rs#127](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/fields.rs#127)
 - [x] TODO: debug_assert_eq!(to-from == size of Self)  [fields.rs#128](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/fields.rs#128)
 - [ ] TODO: expect some codding of signed ints?  [fields.rs#203](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/fields.rs#203)
 - [ ] TODO: should we check `SystemTime` validity in check?  [fields.rs#238](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/fields.rs#238)
 - [ ] TODO: add socketaddr check, for now with only ipv4  [fields.rs#270](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/fields.rs#270)
 - [ ] FIXME: reserve space for future compatibility  [fields.rs#274](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/fields.rs#274)
 - [ ] FIXME: Supporting Ipv6  [fields.rs#292](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/fields.rs#292)
 - [ ] TODO: explain how an signed integer is stored in memory (what codding)  [mod.rs#61](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/mod.rs#61)
 - [ ] TODO: replace by more generic type  [mod.rs#153](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/mod.rs#153)
 - [ ] TODO: implement different  [segments.rs#168](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/segments.rs#168)
 - [ ] TODO: reduce memory allocation  [segments.rs#213](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/segments.rs#213)
 - [ ] TODO: avoid reallocation here using normal implementation of bitvec  [segments.rs#225](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/segments.rs#225)
 - [ ] TODO: refer to difference between json serialization and exonum_json  [serialize/json.rs#5](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/serialize/json.rs#5)
 - [ ] TODO: implement Field for float  [serialize/json.rs#6](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/serialize/json.rs#6)
 - [ ] TODO: remove WriteBufferWraper hack (after refactor storage), should be moved into storage  [serialize/json.rs#7](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/serialize/json.rs#7)
 - [x] TODO: implement owned ExonumJsonDeserialize for big ints  [serialize/json.rs#8](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/stream_struct/serialize/json.rs#8)
 - [ ] TODO: Rewrite Deserialize and Serialize implementation  [src/messages/spec.rs#268](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/messages/spec.rs#268)
 - [ ] TODO: maybe we should write it as sub structure in place?  [src/blockchain/spec.rs#88](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/blockchain/spec.rs#88)
 - [ ] TODO: extract some fields like hash and from_raw into trait  [src/blockchain/spec.rs#114](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/blockchain/spec.rs#114)
 - [ ] TODO: Rewrite Deserialize and Serialize implementation  [src/blockchain/spec.rs#201](https://github.com/vldm/exonum-core/blob/65bbab8164917576c7a37586f92558917988dd33/exonum/src/blockchain/spec.rs#201)

**Comment by DarkEld3r** [comment]
Closed as outdated.
