### ISSUE TITLE
Tracking issue for "highload problems" 

### ISSUE THREAD

**Issue by vldm** [exonum/exonum#199]
When we try to send transactions faster then `exonum` could eat them.
We could get situation where net "stuck" and didn't rise height.

The problem looks complex.
But we can see that it appears after event-loop pool fill. I opened two issue for this.
- [x]  `EventLoopConfig.notify_capacity` pool size https://github.com/exonum/exonum-core/issues/34
- [ ] When event-loop pool fill we can ignore timeout. https://github.com/exonum/exonum-core/issues/197

Additionally we got pr, to make it possible for setting tx mem-pool size from config..
- [x]  Add mempool params to node configuration  https://github.com/exonum/exonum-core/pull/193

Some other issues are relevant to this error.
- [ ] Processing igored tx tooks too long. And make noise in log https://github.com/exonum/exonum-core/issues/198 (this slowdown exonum network on high-load)
- [ ] Consensus on the threshold of 1/3 sleeping validators https://github.com/exonum/exonum-core/issues/15 (amplificate network slowdowns) 
- [x] Network discovery failure via RequestPeers https://github.com/exonum/exonum-core/issues/73 (We can see that in logs one of node didn't connect to other, probably because of https://github.com/exonum/exonum-core/issues/197 )
- [ ] Add log in `consensus.rs:498` (`handle_round_timeout`) so we can check if some node really lock on round.

In logs its look like:
1st node:
```
...
[1498567538 : 609] - [ WARN ] - exonum::node::state - Too many transactions in pool, txs=20000, high_priority=false
[1498567538 : 612] - [ WARN ] - exonum::node::state - Too many transactions in pool, txs=20000, high_priority=false
[1498567538 : 926] - [ INFO ] - exonum::node::consensus - I AM LEADER!!! pool = 20000
[1498567540 : 566] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567540 : 926] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=35
[1498567541 : 805] - [ TRACE ] - btc_anchoring_service::observer - Tries to find lect for the addr: ____
[1498567543 : 565] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567543 : 926] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=36
[1498567546 : 566] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567546 : 926] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=37
[1498567549 : 566] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567549 : 926] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=38
[1498567550 : 926] - [ INFO ] - exonum::node::consensus - I AM LEADER!!! pool = 20000
```

2nd node:
```
...
[1498567538 : 604] - [ WARN ] - exonum::node::state - Too many transactions in pool, txs=20164, high_priority=false
[1498567539 : 840] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=32
[1498567540 : 558] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567541 : 902] - [ TRACE ] - btc_anchoring_service::observer - Tries to find lect for the addr: ____
[1498567542 : 840] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=33
[1498567543 : 557] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567543 : 939] - [ INFO ] - exonum::node::consensus - I AM LEADER!!! pool = 20164
[1498567544 : 740] - [ INFO ] - exonum::node::basic - Received Connect message from *.*.*.*:7777, true
[1498567544 : 741] - [ INFO ] - exonum::node::basic - Send Connect message to *.*.*.*:7777
[1498567544 : 743] - [ INFO ] - exonum::node::basic - Received Connect message from *.*.*.*:7777, true
[1498567544 : 744] - [ INFO ] - exonum::node::basic - Send Connect message to *.*.*.*:7777
[1498567545 : 939] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=34
[1498567546 : 558] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567548 : 840] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=35
[1498567549 : 558] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567551 : 840] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=36
[1498567552 : 202] - [ TRACE ] - btc_anchoring_service::observer - Tries to find lect for the addr: _________
[1498567552 : 558] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567554 : 740] - [ INFO ] - exonum::node::basic - Received Connect message from *.*.*.*:7777, true
[1498567554 : 741] - [ INFO ] - exonum::node::basic - Send Connect message to *.*.*.*:7777
[1498567554 : 743] - [ INFO ] - exonum::node::basic - Received Connect message from *.*.*.*:7777, true
[1498567554 : 744] - [ INFO ] - exonum::node::basic - Send Connect message to *.*.*.*:7777
[1498567554 : 939] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49199, round=37
[1498567555 : 558] - [ WARN ] - exonum::node::consensus - Received consensus message f
```

## 3rd and 4th nodes didn't take leadership.

3th: (looks like `lock`)
```

[1498567359 : 104] - [ WARN ] - exonum::node::state - Too many transactions in pool, txs=20000, high_priority=false
[1498567361 : 56] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49198, round=47
[1498567364 : 55] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49198, round=48
[1498567367 : 55] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49198, round=49
[1498567370 : 56] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49198, round=50
[1498567373 : 56] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49198, round=51
[1498567376 : 55] - [ WARN ] - exonum::node::consensus - ROUND TIMEOUT height=49198, round=52
[1498567377 : 657] - [ INFO ] - exonum::node::basic - Received Connect message from *.*.*.*:7777, true
[1498567377 : 658] - [ INFO ] - exonum::node::basic - Send Connect message to :7777
[1498567377 : 659] - [ INFO ] - exonum::node::basic - Received Connect message from *.*.*.*:7777, true
[1498567377 : 660] - [ INFO ] - exonum::node::basic - Send Connect message to :7777
```
4th: (looks like https://github.com/exonum/exonum-core/issues/197)
```
[1498567538 : 607] - [ WARN ] - exonum::node::state - Too many transactions in pool, txs=20000, high_priority=false
[1498567540 : 561] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567541 : 744] - [ TRACE ] - btc_anchoring_service::observer - Tries to find lect for the addr: _
[1498567543 : 561] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567546 : 561] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567549 : 562] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567552 : 175] - [ TRACE ] - btc_anchoring_service::observer - Tries to find lect for the addr: _
[1498567552 : 562] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567555 : 562] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567558 : 562] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567561 : 562] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567562 : 622] - [ TRACE ] - btc_anchoring_service::observer - Tries to find lect for the addr: _
[1498567564 : 563] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567567 : 562] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567570 : 562] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567573 : 161] - [ TRACE ] - btc_anchoring_service::observer - Tries to find lect for the addr: _
[1498567573 : 562] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567576 : 562] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567579 : 563] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567582 : 563] - [ WARN ] - exonum::node::consensus - Received consensus message from other height: msg.height=49198, self.height=49199
[1498567583 : 502] - [ TRACE ] - btc_anchoring_service::observer - Tries to find lect for the addr: _
```

**Comment by ivan-ochc** [comment]
All subissues were closed/merged
