### ISSUE TITLE
Tracking issue for 0.3

### ISSUE THREAD

**Issue by defuz** [exonum/exonum#265]
### Major features:

- [ ] **Serialization format.** Decide what we do: we use capnp or continue to develop our own format. First of all, we need to prepare a document with a comparative analysis. @vldm 
   - [ ] Make a final decision
   - [ ] ...

- [ ] **Move to RocksDB.** Using TransactionalDB instead of Fork and column families instead index prefixes. @aleksuss #178 
   - [ ] Integrate RockDB as well as LevelDB
   - [ ] Use TranscationDB intead of Fork
   - [ ] Use column families
- [ ] **Parallelization.** Using multiple threads to run Exonum. @alekseysidorov 

  - [ ] Executing a block in a separate thread
  - [ ] Configurable thread pool for tx/signature verification

- [ ] **Services as dynamic libraries.** We should learn how to connect services as shared libraries and how to change the API of services for this. @DarkEld3r #288
- [ ] **DOS resistance.** We should fairly allocate resources for interaction with nodes and have an upper bound on the necessary memory for guaranteed work. @gisochre @YuryYa 
  - [ ] Predictable memory usage for consensus
  - [ ] Allocate resources for network and events

- [ ] **API for dashboard and gathering statistics.** Сollect statistics about Exonum working as time series data and provide all the necessary information for the dashboard through the API. @DarkEld3r #321 

### Minor issues:

- [ ] Dynamic ids for services #65 
- [ ] Add developer notes #8 
- [ ] Implement new leader election algorithm #9 
- [ ] Error handling (and error-chain) #57 
- [ ] Network conectivity loss #73 
- [ ] Persistent storing of sent consensus messages #75 
- [ ] Decompose Block network message #156 
- [ ] Cross-Origin headers for public API #263 
- [ ] Consensus on the threshold of 1/3 sleeping validators #15

**Comment by DarkEld3r** [comment]
What about #97, #244, #245, #248, #212?
I can take any (all) of that except #245.
