### ISSUE TITLE
Managing node through managing API ("RPC")

### ISSUE THREAD

**Issue by defuz** [exonum/exonum#60]
t:
- [x] blockchain-info () - current info on blockchain(currrent height etc.); covered by https://github.com/exonum/exonum-core/pull/131 and earlier
- [x] block-hash () - block hash by height; covered by https://github.com/exonum/exonum-core/pull/131 and earlier
- [x] block-header () - block header with signatures by height/hash; covered by https://github.com/exonum/exonum-core/pull/131
- [x] tx () - return transation by hash; probably, separate method or parameters to remove proof of inclusion into block. covered by https://github.com/exonum/exonum-core/pull/131
- [x] mempool-info () - private; mempool size. Closed as part of https://github.com/exonum/exonum/pull/224
- [x] mempool-list (`hash`) - private; get status (mempool, committed, unknown) of transaction; its body; its location, if committed. Closed as part of https://github.com/exonum/exonum/pull/224
- [x] stop () - stops server; deferred to https://github.com/exonum/exonum-core/issues/149
- [ ] help () - command help. Not actual for restful api. Documentation instead. 
- [x] generate () - generate one or more blocks in demo mode??; not needed. we're in demo mode by default  :children_crossing: . 
- [x] propose-get () - return propose ; deferred to https://github.com/exonum/exonum-core/issues/151
- [x] propose-submit () - broadcast propose; deferred to https://github.com/exonum/exonum-core/issues/151
- [x] (prevote|precommit)-(get|submit) - handles to atomic operations of byzantine behavior deferred to https://github.com/exonum/exonum-core/issues/151
- [x]  viewing consensus messages from other node? Currently these aren't persisted, besides precommits. - deferred to https://github.com/exonum/exonum-core/issues/152. 
- [x] prioritize () - change tx priority in pool. deferred to https://github.com/exonum/exonum-core/issues/150
- [x] network-info () - private; static protocol_id, static network_id, list of mounted services. Closed as part of https://github.com/exonum/exonum/pull/224
- [x] network-totals () - traffic etc (we don't collect this info now) ; deferred to https://github.com/exonum/exonum-core/issues/153
- [x] peer-info () - private; get all incoming/outgoing connections; peers map of state; actual reconnects. Closed as part of https://github.com/exonum/exonum/pull/224
- [x] peer-add (`ip-address`) - private; generate Event(ConnecTo(`ip-address`)) . Closed as part of https://github.com/exonum/exonum/pull/224
- [x] peer-remove () - deferred to be contolled by reading config during node restart of https://github.com/exonum/exonum-core/issues/14
