### ISSUE TITLE
Tracking issue for 0.1 release

### ISSUE THREAD

**Issue by defuz** [exonum/exonum#67]
### Features & code changes:

@defuz:

- [x] Implement iterators for storage, refactoring storage key #7 #58
- [x] Panic handling during transaction execution #59
- [ ] Add developer notes #8 

@alekseysidorov:

- [x] Combine public/private API endpoints from services #66 #53
-  ~~Dynamic IDs for services #65~~

@gisochre:

- [ ] Network discovery failure via RequestPeers #73
- [x] transaction location within block #77

@DarkEld3r:

- [x] "Propose timeout" refactoring #49
- [x] Review methods and functions naming into whole project #55
- [x] Sending status message after every block and reset timeout #63
- [x] Separate keys for signing consensus messages and transactions #62
- [x] Documenting consensus messages #48

@vldm:

- [x] Ser/de, refactoring messages #17 #32
- [x] Whitelist support for full nodes #14 
- [x] Generic fabric for clap configuration (assistant @alekseysidorov) #61
- [x] Tx generator, running benchmarks #54 
- [x] Handling of mempool filling #64
- [x] Verify profiling #52 
- [x] Managing node through managing API ("RPC") (assistant @alekseysidorov) #60

@DenisKolodin:

- [x] Modifying block structure #138 

### Documentation #111:

Each responsible provide separate PR which add `#![deny(missing_docs)]` to their modules. After that, we add `#![deny(missing_docs)]` for overall `exonum`.

- [x] Module `blockchain` @alekseysidorov 
- [x] Messages, storage values and seriaization @vldm 
- [x] Module `node` @DarkEld3r 
- [x] Module `storage` @defuz

### Release process 

TBD
